[package]
name = "nscn"
version = "0.1.0"
authors = ["SardineFish <Sardine@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "socks"] }
tokio = { version = "1", features = ["full"] }
mongodb = "2.0.0-alpha"
redis = { version = "0.20.0", features = ["tokio-comp"] }
serde = "1.0.124"
serde_json = "1.0.64"
log = "0.4.0"
env_logger = "0.8.3"
chrono = "0.4.19"
lazy_static = "1.4.0"
rand = { version = "0.8.3", features = ["small_rng"] }
futures = "0.3.13"
httparse = "1.3.5"
openssl = "0.10.33"