[package]
name = "nscn-cli"
version = "0.1.0"
authors = ["SardineFish <Sardine@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nscn = { path = "scanner_service" }
tokio = { version = "1", features = ["full", "sync"] }